name: Build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Rust toolchain
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # Cache the cargo registry and target directory
      - uses: Swatinem/rust-cache@v2

      # Build for Windows
      - name: Build for Windows
        run: cargo build --verbose --release --all-targets

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: composite-hkx-conversion
          path: |
            ./target/release/composite-hkx-conversion.exe
